version: 0.0
os: linux
files:
  - source: /DuoCord-0.1.jar
    destination: /tmp
hooks:
  BeforeInstall:
    - location: setup_env.sh
      timeout: 300
  ApplicationStart:
    - location: start_bot.sh
      timeout: 300
  ApplicationStop:
    - location: stop_bot.sh
      timeout: 300
