version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo add env variables?
  build:
    commands:
      - echo Build started on `date`
      - chmod +x ./gradlew
      - ./gradlew build
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - build/libs/DuoCord-0.1.jar
    - appspec.yml
    - scripts/setup_env.sh
    - scripts/start_bot.sh
    - scripts/stop_bot.sh
  discard-paths: yes