name: Deploy
on:
  workflow_run:
    workflows: [ "Test and Build" ]
    types:
      - completed

jobs:

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the files
        uses: actions/checkout@v4
      - name: Set up JDK 17 for Build
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'zulu'
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2
        with:
          envkey_SSH_KEY: ${{ secrets.SSH_KEY }}
          envkey_DISCORD_BOT_KEY: ${{ secrets.DISCORD_BOT_KEY }}
          envkey_REDIS_HOST: ${{ secrets.REDIS_HOST }}
          envkey_REDIS_PORT: ${{ secrets.REDIS_PORT }}
          envkey_REDIS_PASS: ${{ secrets.REDIS_PASS }}
          directory: .
          fail_on_empty: true
          file_name: .env

      - name: Deploy to EC2
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}

      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd home
            chmod +x ./gradlew
            ./gradlew clean build

      - run: |
          ls
          chmod +x ./gradlew
          ./gradlew clean build