name: Test and Build
on:
  push:
    branches: [ master ]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: zulu
      - name: Run tests with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew clean test integTest

  build:
    needs: test
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v4
      - name: Set up JDK 17 for Build
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'zulu'
      - run: |
          chmod +x ./gradlew
          ./gradlew clean build