name: Test and Build
on:
  push:
    branches: [ master ]
jobs:


  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: zulu
      - name: Run tests with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew clean test integTest

  build:
    needs: test
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v4
      - name: Set up JDK 17 for Build
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'zulu'
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2
        with:
          envkey_SSH_KEY: ${{ secrets.SSH_KEY }}
          envkey_DISCORD_BOT_KEY: ${{ secrets.DISCORD_BOT_KEY }}
          envkey_REDIS_HOST: ${{ secrets.REDIS_HOST }}
          envkey_REDIS_PORT: ${{ secrets.REDIS_PORT }}
          envkey_REDIS_PASS: ${{ secrets.REDIS_PASS }}
          directory: .
          fail_on_empty: true
          file_name: .env

      - run: |
          ls
          chmod +x ./gradlew
          ./gradlew clean build